spring:
  profiles:
    active: docker
  application:
    name: medlearn

  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/medlearn_db
    username: medlearn
    password: Medlearn@123
    driver-class-name: org.postgresql.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  # Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: duongkt.st.2005@gmail.com
    password: issv ueis kdqm fkwk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # OAuth2 (Google, Facebook)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1056466740527-b4dqe4jjo5miauiuq5bi3rrd4tfdh56d.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
#          facebook:
#            client-id: YOUR_FACEBOOK_APP_ID
#            client-secret: YOUR_FACEBOOK_APP_SECRET
#            scope:
#              - email
#              - public_profile

server:
  port: 8080

# JWT
jwt:
  secret: 1if6e0DWXP9angeAJj2oB3nwEvxmAApXpNEpsGoVfKdHv7k1fVY2GJL4kyuL1qxrmzK0a6Kr55meKeBXiY7wmTicmzxThlIEDpOi5N2W35R7c9LEqO4yDZYrVmhqMgl8KCPPCCSPJD1O6qpbYqyeIOCNCpRaGQ9fU5yl7yC8poZcqK0nYPM3lJbmYxp2ERPDIdYlAJmimu3zf3Wrt81shQt9mNs9NzgoM9LZSXWuAtgGVctu5zma3O2rA9UTSzuuVHnLagWon5vSJ12CSUBRe7WLDOEzMExAigRxySMTvoZVxaGER0PSJPgCqIlzHq7zpeNvgy7BGg35SXDUpj6Q9mrzzoseve2HNQhrAb4t
  expiration: 86400000
  refresh-expiration: 604800000
  password-reset-expiry-hours: 1

auth:
  rate-limit:
    max-attempts: 5
    block-duration-minutes: 15

# App
app:
  url: http://localhost:8080

email:
  verification:
    expiry-hours: 24